import { Note } from "@/types/note";

const notes: Note[] = [
  {
    id: "calculus-ii",
    fileType: "PDF",
    subject: "Math",
    accentColor: "#e8e0ff",
    accentTextColor: "#5b21b6",
    avatarColor: "#ddd6fe",
    headerText: "Calculus II — Midterm Summary",
    descriptionText:
      "Derivatives, integrals and the theorems you actually need before the exam. Clean structure, zero fluff.",
    studentName: "Kornel P.",
    noteReleaseDate: "2 days ago",
    downloadCount: 214,
    starGrade: 4.9,
    isFeatured: true,
  },
  {
    id: "thermodynamics",
    fileType: "DOCX",
    subject: "Physics",
    accentColor: "#d8f5de",
    accentTextColor: "#166534",
    avatarColor: "#bbf7d0",
    headerText: "Thermodynamics cheat sheet",
    descriptionText: "Laws, formulas and common exam traps in one page.",
    studentName: "Ania K.",
    noteReleaseDate: "5 days ago",
    downloadCount: 88,
    starGrade: 4.6,
  },
  {
    id: "algorithms",
    fileType: "PDF",
    subject: "CS",
    accentColor: "#d6eaff",
    accentTextColor: "#1e40af",
    avatarColor: "#bfdbfe",
    headerText: "Algorithms — Sorting & Complexity",
    descriptionText: "Big-O cheat sheet with examples for each sort.",
    studentName: "Marek W.",
    noteReleaseDate: "1 week ago",
    downloadCount: 156,
    starGrade: 4.8,
  },
  {
    id: "organic-reactions",
    fileType: "PDF",
    subject: "Chemistry",
    accentColor: "#ffe4c4",
    accentTextColor: "#9a3412",
    avatarColor: "#fed7aa",
    headerText: "Organic reactions map",
    descriptionText: "Mechanisms grouped by functional group.",
    studentName: "Ola R.",
    noteReleaseDate: "3 days ago",
    downloadCount: 67,
    starGrade: 4.4,
  },
  {
    id: "cell-biology",
    fileType: "PDF",
    subject: "Biology",
    accentColor: "#fce7f3",
    accentTextColor: "#9d174d",
    avatarColor: "#fbcfe8",
    headerText: "Cell biology flash notes",
    descriptionText: "Organelles, mitosis and key exam diagrams.",
    studentName: "Tomek L.",
    noteReleaseDate: "4 days ago",
    downloadCount: 102,
    starGrade: 4.7,
  },
];

export default notes;
